### ISSUE TITLE
Unable to add multiple custom attributes to the cognito pool

### ISSUE THREAD

**Issue by simplesethia** [jmaleonard/serverless-cognito-add-custom-attributes#4]
We are trying to user serverless to configure cognito pool and add custom attributes using the serverless-cognito-add-custom-attributes plugin. When we try to add more than 2 custom attributes, it fails to add them without any error on the terminal.
When we add using two attributes, it sometimes add both the custom attribute, sometimes one and sometime none.
[serverless.yml.txt](https://github.com/michaelduminy/serverless-cognito-add-custom-attributes/files/3120468/serverless.yml.txt)

**Comment by simplesethia** [comment]
After further debug, we found the following error on the console -
ServerlessError: Invalid write attributes specified while updating a client
    at /Users/pro/.nvm/versions/node/v12.0.0/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:295:11
    at processTicksAndRejections (internal/process/task_queues.js:88:5) {
  name: 'ServerlessError',
  statusCode: 400,
  providerError: InvalidParameterException: Invalid write attributes specified while updating a client
      at Request.extractError (/Users/pro/.nvm/versions/node/v12.0.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/protocol/json.js:51:27)
      at Request.callListeners (/Users/pro/.nvm/versions/node/v12.0.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (/Users/pro/.nvm/versions/node/v12.0.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/Users/pro/.nvm/versions/node/v12.0.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:683:14)
      at Request.transition (/Users/pro/.nvm/versions/node/v12.0.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/Users/pro/.nvm/versions/node/v12.0.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /Users/pro/.nvm/versions/node/v12.0.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/Users/pro/.nvm/versions/node/v12.0.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/Users/pro/.nvm/versions/node/v12.0.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:685:12)
      at Request.callListeners (/Users/pro/.nvm/versions/node/v12.0.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at Request.emit (/Users/pro/.nvm/versions/node/v12.0.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/Users/pro/.nvm/versions/node/v12.0.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:683:14)
      at Request.transition (/Users/pro/.nvm/versions/node/v12.0.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/Users/pro/.nvm/versions/node/v12.0.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /Users/pro/.nvm/versions/node/v12.0.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/Users/pro/.nvm/versions/node/v12.0.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/Users/pro/.nvm/versions/node/v12.0.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/request.js:685:12)
      at Request.callListeners (/Users/pro/.nvm/versions/node/v12.0.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at callNextListener (/Users/pro/.nvm/versions/node/v12.0.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
      at IncomingMessage.onEnd (/Users/pro/.nvm/versions/node/v12.0.0/lib/node_modules/serverless/node_modules/aws-sdk/lib/event_listeners.js:299:13)
      at IncomingMessage.emit (events.js:201:15)
      at IncomingMessage.EventEmitter.emit (domain.js:471:20)
      at endReadableNT (_stream_readable.js:1130:12)
      at processTicksAndRejections (internal/process/task_queues.js:83:17) {
    message: 'Invalid write attributes specified while updating a client',
    code: 'InvalidParameterException',
    time: 2019-05-02T07:57:22.330Z,
    requestId: 'ea6c6712-6caf-11e9-b198-0b817f7308fa',
    statusCode: 400,
    retryable: false,
    retryDelay: 59.357808297067564
  }
}
 
  Cognito Add Custom Attributes Plugin Error -------------
 
  Invalid write attributes specified while updating a client

**Comment by simplesethia** [comment]
Per the documentation that I have read so far on the cognito custom attributes, I have come to know that writeable attributes when not specified as required would lead to InvalidParameterException and currently custom attributes does not support required attributes. The error that I get when I set the required as true for the custom attributes - 
Cognito Add Custom Attributes Plugin Error -------------
  Required custom attributes are not supported currently.

**Comment by michaelduminy** [comment]
Hi @simplesethia, thanks for the bug report. In your example `yml` above you are specifying one custom attribute per pool. Can you please try to specify all the custom attributes that belong in a single pool in that pool?

Like this:
```
custom:
  CognitoAddCustomAttributes: 
    -
      CognitoUserPoolIdOutputKey: "UserPoolId"
      CognitoUserPoolClientIdOutputKey: "UserPoolClientId"
      CustomAttributes: 
        -
          AttributeDataType: "String"
          DeveloperOnlyAttribute: false
          Mutable: true
          Name: "createdBy"
          Required: false
          StringAttributeConstraints:
            MaxLength: "256"
            MinLength: "0"
        -
          AttributeDataType: "String"
          DeveloperOnlyAttribute: false
          Mutable: true
          Name: "deletedBy"
          Required: false
          StringAttributeConstraints:
            MaxLength: "256"
            MinLength: "0"
```

**Comment by cadentic** [comment]
https://docs.aws.amazon.com/en_us/cognito/latest/developerguide/cognito-user-pools-app-integration.html 
custom attributes are not supported in the Amazon Cognito user pool?
